### PR TITLE
SignalR package renames

### PR DESCRIPTION
**Pull request by moozzyk**
https://github.com/aspnet/SignalR/pull/800

### CODE REVIEW

**Comment by moozzyk** [comment]
@ryanbrandenburg @pranavkm @natemcmaster  ⌚️

**Review by ryanbrandenburg — APPROVED** [review]

**Comment by natemcmaster** [comment]
Did you follow the rest of the new package creation procedures? https://github.com/aspnet/Coherence-Signed/wiki/New-package-Id-creation

**Comment by moozzyk** [comment]
I did not do 6. - the link is broken.

**Comment by natemcmaster** [comment]
I updated the link.

**Pull request merged**
