### PR TITLE
Don't ship Kestrel.Transport.Sockets for 2.0

### PR DESCRIPTION
**Pull request by halter73**

### CODE REVIEW

**Comment by halter73** [comment]
Ping @muratg

**Comment by muratg** [comment]
Do we need to update the runtime package store manifest as well?

**Comment by halter73** [comment]
https://github.com/aspnet/MetaPackages/pull/170 is my PR to update the metapackage.

**Comment by halter73** [comment]
@muratg A 2.0.0-preview1 Kestrel.Transport.Sockets package is already [on NuGet.org](https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets/2.0.0-preview1-final). That's not a problem, right?

**Comment by muratg** [comment]
@halter73 should be OK, and it looks like we'll be pushing preview2 as well (since it's already in the RPS).  I think we'll end up unlisting both.

**Review by muratg — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]

**Pull request merged**
