### PR TITLE
sequentially publish packages

### PR DESCRIPTION
**Pull request by JunTaoLuo**
@pranavkm Something like this?

### CODE REVIEW

**Comment by pranavkm** [comment]
As long as it builds :shipit:

**Comment by pranavkm** [comment]
Can you also add a try - catch here - https://github.com/aspnet/Coherence/blob/dev/makefile.shade#L85

**Comment by JunTaoLuo** [comment]
and just nop in catch?

**Comment by pranavkm** [comment]
Yup.

**Pull request merged**
