### PR TITLE
Remove Microsoft.Owin.Security.Interop from packages.csv

### PR DESCRIPTION
**Pull request by Eilon**
See https://github.com/aspnet/Security/pull/1202 for the cause for removal

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Review by mikeharder — APPROVED** [review]

**Comment by Eilon** [comment]
@Tratcher / @mikeharder - any chance one of you can port to `dev`? I'm not enough of a git expert to do that without messing it up 😄

**Comment by mikeharder** [comment]
I will port to dev

**Comment by mikeharder** [comment]
Merged to dev: https://github.com/aspnet/Coherence/commit/f0882d0f37f4f443455d6e6ef739aed2e0130a6c

**Comment by mikeharder** [comment]
@Eilon: Delete branch?

**Pull request merged**
