### PR TITLE
Create a new shipoob category for packages that ship separate from the main train

### PR DESCRIPTION
**Pull request by Tratcher**
This should cause the creation of a new shipoob directory in the drops folder. From there I can modify coherence-signed to sign these packages without mixing them with the normal shipping packages.

### CODE REVIEW

**Review by muratg — APPROVED** [review]

**Comment by pranavkm** [comment]
:shipit:

**Review by Eilon — APPROVED** [review]
Approved-ish. Can we add a readme.txt or packages.readme.txt to this same folder that says what the columns mean, and what the "enum" values are? Then merge.

**Comment by Tratcher** [comment]
No longer planning this for preview1, only dev.

**Review by JunTaoLuo — APPROVED** [review]

**Comment by Eilon** [comment]
Reminder: do this: https://github.com/aspnet/Coherence/pull/204#pullrequestreview-36143356

**Pull request closed without merging**
