### PR TITLE
Temporarily skip PlatformAbstractions

### PR DESCRIPTION
**Pull request by pranavkm**
cc @anurse \ @Eilon 

PlatformAbstractions is a bit messed up at this point. Temporarily skipping it from coherence verification until we sort it out.

### CODE REVIEW

**Comment by pranavkm** [comment]
https://github.com/aspnet/Coherence/issues/47

**Comment by anurse** [comment]
Ah, the package verifier. Yeah, unfortunately dotnet-cli doesn't create equivalent packages yet. We should definitely avoid continuing to exclude things and work on filing and fixing the issues. But for now this seems like the best way to unblock this work.

**Comment by davidfowl** [comment]
Whats the issue with it?

**Comment by anurse** [comment]
Well I'm pretty sure it checks if the Assembly versions match up, which they definitely won't because of dotnet/cli#398

**Pull request merged**
